### ISSUE TITLE
oUF version for legion branch?

### ISSUE THREAD

**Issue by SanUI** [brendanblackwood/oUF_Hank#11]
I'm having trouble with oUF_Hank on the legion beta with a paladin. There's a problem with the class icons, but I assume it's a oUF problem. Which version are you using? There have been quite some changes with the per-class-power, so more trouble is expected :)

**Comment by brendanblackwood** [comment]
I forked oUF and merged the legion patches from p3lim and ls: https://github.com/brendanblackwood/oUF. Try using that and let me know if you still have problems.

**Comment by SanUI** [comment]
That works, thank you!
