### ISSUE TITLE
Wrong call to UnitAura?

### ISSUE THREAD

**Issue by SanUI** [brendanblackwood/oUF_Hank#15]
Hey, I just had a look at the differences of your hank vs mine, and I noticed [this](https://github.com/brendanblackwood/oUF_Hank/blob/master/hank.lua#L316) call to `UnitAura`. I think it's not quite right, according to https://wow.gamepedia.com/API_UnitAuraand my own testing you're not correctly getting the dtype.

**Comment by brendanblackwood** [comment]
Good catch. I've updated it here and tagged a new version: https://github.com/brendanblackwood/oUF_Hank/commit/81948302d7957da073e5b99163e8bd222e62068d
